packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@astrojs/react': ^4
  '@aws-sdk/client-s3': ^3
  '@aws-sdk/s3-request-presigner': ^3
  '@babel/core': ^7.25.2
  '@biomejs/biome': ^2.4.14
  '@expo/vector-icons': ^14.0.0
  '@hookform/resolvers': ^5
  '@playwright/test': ^1
  '@prisma/adapter-pg': ^7
  '@prisma/client': ^7
  '@radix-ui/react-switch': ^1
  '@tailwindcss/postcss': ^4
  '@tailwindcss/vite': ^4
  '@tanstack/react-query': ^5
  '@tanstack/react-router': ^1
  '@tanstack/router-plugin': ^1
  '@trpc/client': ^11
  '@trpc/server': ^11
  '@trpc/tanstack-react-query': ^11
  '@types/cors': ^2
  '@types/nodemailer': ^6
  '@types/react': ^19
  '@types/react-dom': ^19
  '@types/web-push': ^3.6.4
  '@vitejs/plugin-react': ^4
  arktype: ^2
  astro: ^5
  better-auth: 1.6.9
  class-variance-authority: ^0.7
  clsx: ^2
  consola: ^3
  cors: ^2
  date-fns: ^4
  date-fns-tz: ^3
  dotenv: ^16
  expo: ~55.0.0
  expo-haptics: ~14.0.1
  expo-router: ~5.0.0
  expo-status-bar: ~2.2.0
  ioredis: ^5
  lucide-react: ^0.511
  nitropack: 2.13.4
  nodemailer: ^6
  prisma: ^7
  radix-ui: ^1
  react: 19.0.0
  react-dom: 19.0.0
  react-hook-form: ^7
  react-native: 0.79.0
  react-native-safe-area-context: ^5.0.0
  react-native-screens: ~4.10.0
  resend: ^4
  stripe: ^17
  tailwind-merge: ^3
  tailwindcss: ^4
  turbo: ^2.9.9
  typescript: ^5.9.3
  vite: ^6
  web-push: ^3.6.7
  zod: ^4
